In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import streamlit as st
from io import BytesIO
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [3]:
df = pd.read_csv('auctioncars.csv')

In [6]:
df.head(3)

,RefId,IsBadBuy,PurchDate,VehYear,VehicleAge,Make,Model,Color,Transmission,Nationality,...,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,2006,3,MAZDA,MAZDA3,RED,AUTO,OTHER ASIAN,...,13600.0,7451.0,8552.0,11597.0,12409.0,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,2004,5,DODGE,1500 RAM PICKUP 2WD,WHITE,AUTO,AMERICAN,...,12572.0,7456.0,9222.0,11374.0,12791.0,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,2005,4,DODGE,STRATUS V6,MAROON,AUTO,AMERICAN,...,8457.0,4035.0,5557.0,7146.0,8702.0,33619,FL,4900.0,0,1389